#!/bin/bash
fileforcracking() {

    read -p "Enter Your File Name with Extension: " filename
    echo ""
    echo "Warning: Don't enter '.' when entering your extension.."
    echo ""
    read -p "Enter Your File Extension (pdf, 7z, zip, rar): " extension

    if [ -f "$filename" ]; then
        echo "File Found"
        if [[ "$extension" == "pdf" || "$extension" == "7z" || "$extension" == "zip" || "$extension" == "rar" ]]; then 
            "$extension"2john "$filename" > "$filename".txt
            john "$filename".txt
        else
            echo "Enter a valid extension for the file (pdf, 7z, zip, rar)"
        fi
    else
        echo "File not found"
    fi
}

while true; do
    clear
    figlet "Vraj ' s  Team  : )"
    echo "Created by Vraj's team :)"
    echo "This tool is used to crack the password of the following file types: 1) pdf 2) 7z 3) zip 4) rar"
    echo "Make sure that file you want to crack is in same directory where this tool is install :)"
    echo " "
    echo " " 
    echo "Password Cracking Tool"
    echo "=========================="
    echo "1. Select The File For Cracking The Password:"
    echo "2. Exit"
    read -p "Choose an option [1-2]: " choice

    case $choice in
        1)
            fileforcracking
            ;;
        2)
            echo "Exiting the tool...."
            exit 0
            ;;
        *)
            echo "Invalid option. Please choose between 1 and 2."
            ;;
    esac

    # Pause to let the user see the result
    read -p "Press Enter to continue..."
done
